build:
	javac Curatare.java Fortificatii.java Beamdrone.java Curse.java

run-p1:
	java Curatare
run-p2:
	java Fortificatii
run-p3:
	java Beamdrone
run-p4:
	java Curse

clean:
	rm -rf Curatare Fortificatii Beamdrone Curse
